apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: shubhamkushwah123/medicure:1.0
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"

---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
  labels:
    app: medicure
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 31085
